filebeat.inputs:
- type: log
  paths: 
    - '/nginx-logs/main_access.log'

output.elasticsearch:
  hosts: ["http://192.200.0.102:9200","192.200.0.102:5044"]
  indices:
    - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"

logging.json: true
logging.metrics.enabled: false
