version: '3.7'

services:
  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  elasticsearch:
    image: elasticsearch:7.17.9
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - cluster.name=es-netology-hw
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk

  kibana:
    container_name: kibana
    image: kibana:7.17.9
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elk

  logstash:
    container_name: logstash
    image: logstash:7.17.20
    volumes:
      - /home/jinon/ELK-netology-hw/pipeline/:/usr/share/logstash/pipeline/
      - /home/jinon/ELK-netology-hw/settings/:/usr/share/logstash/config/
    networks:
      - elk

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - /home/jinon/ELK-netology-hw/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080
    networks:
      - elk

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.9
    command: --strict.perms=false
    user: root
    volumes:
      - /home/jinon/ELK-netology-hw/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - elk

volumes:
  elasticsearch-data:
    driver: local

networks:
  elk:
    driver: bridge